name: Java Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean compile
    - name: Execute Maven  
      run: mvn compile exec:java -Dexec.mainClass="hello.HelloWorld"

    - name: Create class directory
      run: mkdir -p target/classes
    - name: Move class files
      run: |
            shopt -s dotglob nullglob
            for file in target/classes/*; do
            if [ -f "$file" ]; then
            mv "$file" target/classes/
            fi
            done    
